fix conditional tagging logic

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -91,11 +91,14 @@ jobs:
             MAJOR=$((MAJOR + 1))
             MINOR=0
             PATCH=0
+            SHOULD_DEPLOY=true
           elif [[ "$SCHEMA_MAJOR" -eq "$MAJOR" && "$SCHEMA_MINOR" -gt "$MINOR" ]]; then
             MINOR=$((MINOR + 1))
             PATCH=0
+            SHOULD_DEPLOY=true
           elif [[ "$SCHEMA_MAJOR" -eq "$MAJOR" && "$SCHEMA_MINOR" -eq "$MINOR" && "$SCHEMA_PATCH" -gt "$PATCH" ]]; then
             PATCH=$((PATCH + 1))
+            SHOULD_DEPLOY=true
           else
             echo "Schema version is not greater than last published version. No deployment needed."
             exit 0
@@ -110,27 +113,29 @@ jobs:
           echo "NEW_PUBLISHED_VERSION: ${{ steps.compare_versions.outputs.new_published_version }}"
         working-directory: '${{ matrix.value }}'
       - name: Set version in version.json
-        if: contains(env.VERSIONED_SUBGRAPHS, matrix.value)
+        if: contains(env.VERSIONED_SUBGRAPHS, matrix.value) && steps.compare_versions.outputs.should_deploy == true
         run: |
           NEW_PUBLISHED_VERSION=${{ steps.compare_versions.outputs.new_published_version }}
           SCHEMA_VERSION=${{ steps.get_schema_version.outputs.schema_version }}
           echo "{\"schemaVersion\": \"$SCHEMA_VERSION\", \"publishedVersion\": \"$NEW_PUBLISHED_VERSION\"}" > version.json
         working-directory: '${{ matrix.value }}'
       - name: Set Version in version.ts for version entity
-        if: contains(env.VERSIONED_SUBGRAPHS, matrix.value)
+        if: contains(env.VERSIONED_SUBGRAPHS, matrix.value) && steps.compare_versions.outputs.should_deploy == true
         run: npm run set-version
         working-directory: '${{ matrix.value }}'
-      - name: Commit version change
-        if: contains(env.VERSIONED_SUBGRAPHS, matrix.value)
+      - name: Prepare Manifest
+        if: matrix.value == 'polygon-digital-carbon' || matrix.value == 'carbonmark'
+        run: npm run prepare-matic
+        working-directory: '${{ matrix.value }}'
+      - name: Commit all changes
+        if: contains(env.VERSIONED_SUBGRAPHS, matrix.value) && steps.compare_versions.outputs.should_deploy == true
         run: |
           NEW_PUBLISHED_VERSION=${{ steps.compare_versions.outputs.new_published_version }}
 
           git config user.email "deploy-action@carbonmark.com"
           git config user.name "deploy-action"
 
-          git add version.json
-
-          git commit -m "action: update version.json to publishedVersion: $NEW_PUBLISHED_VERSION for ${{ matrix.value }}"
+          git commit -am "action: update to publishedVersion: $NEW_PUBLISHED_VERSION for ${{ matrix.value }}"
 
           if [[ "${GITHUB_REF}" == "refs/heads/"* ]]; then
             BRANCH_NAME=${GITHUB_REF#refs/heads/}
@@ -142,13 +147,13 @@ jobs:
           fi
 
           echo "Pushing to branch: $BRANCH_NAME"
-          
+
           # git push origin $BRANCH_NAME
           # @todo remove this before any merge. Only for testing actions
-          git push --force origin $BRANCH_NAME   
+          git push --force origin $BRANCH_NAME
         working-directory: '${{ matrix.value }}'
       - name: Tag the commit with the new version
-        if: contains(env.VERSIONED_SUBGRAPHS, matrix.value)
+        if: contains(env.VERSIONED_SUBGRAPHS, matrix.value) && steps.compare_versions.outputs.should_deploy == true
         run: |
           NEW_VERSION=${{ steps.compare_versions.outputs.new_published_version }}
           echo "NEW_VERSION: $NEW_VERSION"
@@ -163,51 +168,64 @@ jobs:
           # @todo remove this before any merge. Only for testing actions
           git push --force origin $BRANCH_NAME --tags
         working-directory: '${{ matrix.value }}'
-      - name: Prepare Manifest
-        if: matrix.value == 'polygon-digital-carbon' || matrix.value == 'carbonmark'
-        run: npm run prepare-matic
-      # Generate code and check for uncommitted changes
-      # https://github.com/marketplace/actions/check-uncommitted-changes
-      - name: Generate Subgraph Code
-        run: npm run codegen
-        working-directory: '${{ matrix.value }}'
-      - name: Check for uncommitted changes
-        id: check-changes
-        uses: mskri/check-uncommitted-changes-action@v1.0.1
-      - name: Evaluate if there are changes
-        if: steps.check-changes.outputs.outcome == failure()
-        run: echo "There are uncommitted changes - execute 'npm run codegen' locally and commit the generated files!"
+      # # Generate code and check for uncommitted changes
+      # # https://github.com/marketplace/actions/check-uncommitted-changes
+      # - name: Generate Subgraph Code
+      #   run: npm run codegen
+      #   working-directory: '${{ matrix.value }}'
+      # - name: Check for uncommitted changes
+      #   id: check-changes
+      #   uses: mskri/check-uncommitted-changes-action@v1.0.1
+      # - name: Evaluate if there are changes
+      #   if: steps.check-changes.outputs.outcome == failure()
+      #   run: echo "There are uncommitted changes - execute 'npm run codegen' locally and commit the generated files!"
 
-      - name: Build Subgraph
-        run: npm run build
-        working-directory: '${{ matrix.value }}'
-      # TODO: add matchstick test suite
-      # - name: Run Tests
-      #   run: npm run test
-      #   working-directory: "${{ matrix.value }}"
+      # - name: Build Subgraph
+      #   run: npm run build
+      #   working-directory: '${{ matrix.value }}'
+      # # TODO: add matchstick test suite
+      # # - name: Run Tests
+      # #   run: npm run test
+      # #   working-directory: "${{ matrix.value }}"
 
-      - name: Staging or not
-        id: staging_or_not
-        run: |
-          echo "short_sha=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
+      # - name: Staging or not
+      #   id: staging_or_not
+      #   run: |
+      #     echo "short_sha=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
 
-          if [ $REF == "refs/heads/staging" ]
-          then
-              PREFIX="staging-"
-          fi;
+      #     if [ $REF == "refs/heads/staging" ]
+      #     then
+      #         PREFIX="staging-"
+      #     fi;
 
-          if [[ "${{ matrix.value }}" =~ .*"-".*"-carbon".* ]]
-          then
-              echo "subgraph=${PREFIX}${{ matrix.value }}" >> $GITHUB_OUTPUT
-          else
-              echo "subgraph=${PREFIX}klimadao-${{ matrix.value }}" >> $GITHUB_OUTPUT
-          fi
-        env:
-          REF: ${{ github.ref }}
-      - name: Deploy Subgraph to Studio
-        run: ../node_modules/.bin/graph deploy --studio --deploy-key ${{ secrets.SUBGRAPH_STUDIO_DEPLOY_KEY }} ${{ steps.staging_or_not.outputs.subgraph }} --version-label ${{ steps.compare_versions.outputs.new_published_version }}
-        working-directory: '${{ matrix.value }}'
-      - name: Deploy Subgraph to Alchemy Hosted Service
-        if: ${{ matrix.value == 'carbonmark' || matrix.value == 'polygon-digital-carbon' || matrix.value == 'pairs' || matrix.value == 'ethereum-bridged-carbon'}}
-        run: ../node_modules/.bin/graph deploy ${{ steps.staging_or_not.outputs.subgraph }} --deploy-key ${{ secrets.SUBGRAPH_ALCHEMY_HOSTED_SERVICE_DEPLOY_KEY }} --node https://subgraphs.alchemy.com/api/subgraphs/deploy --ipfs https://ipfs.satsuma.xyz --version-label ${{ steps.compare_versions.outputs.new_published_version }}
-        working-directory: '${{ matrix.value }}'
+      #     if [[ "${{ matrix.value }}" =~ .*"-".*"-carbon".* ]]
+      #     then
+      #         echo "subgraph=${PREFIX}${{ matrix.value }}" >> $GITHUB_OUTPUT
+      #     else
+      #         echo "subgraph=${PREFIX}klimadao-${{ matrix.value }}" >> $GITHUB_OUTPUT
+      #     fi
+      #   env:
+      #     REF: ${{ github.ref }}
+      # - name: Deploy Subgraph to Studio
+      #   if: ${{ !contains(fromJson(env.VERSIONED_SUBGRAPHS), matrix.value) || (contains(fromJson(env.VERSIONED_SUBGRAPHS), matrix.value) && steps.compare_versions.outputs.should_deploy == 'true') }}
+      #   run: |
+      #     if contains(${VERSIONED_SUBGRAPHS}, ${matrix.value}); then
+      #       VERSION_LABEL="${{ steps.compare_versions.outputs.new_published_version }}"
+      #     else
+      #       VERSION_LABEL=$(git rev-parse --short "${GITHUB_SHA}")
+      #     fi
+
+      #     ../node_modules/.bin/graph deploy --studio --deploy-key ${{ secrets.SUBGRAPH_STUDIO_DEPLOY_KEY }} "${{ steps.staging_or_not.outputs.subgraph }}" --version-label "$VERSION_LABEL"
+      #   working-directory: '${{ matrix.value }}'
+      # - name: Deploy Subgraph to Alchemy Hosted Service
+      #   if: ${{ (matrix.value == 'carbonmark' || matrix.value == 'polygon-digital-carbon' || matrix.value == 'pairs' || matrix.value == 'ethereum-bridged-carbon') && (!contains(fromJson(env.VERSIONED_SUBGRAPHS), matrix.value) || (contains(fromJson(env.VERSIONED_SUBGRAPHS), matrix.value) && steps.compare_versions.outputs.should_deploy == 'true')) }}
+      #   run: |
+      #     if contains(${VERSIONED_SUBGRAPHS}, ${matrix.value}); then
+      #       VERSION_LABEL="${{ steps.compare_versions.outputs.new_published_version }}"
+      #     else
+      #       VERSION_LABEL=$(git rev-parse --short "${GITHUB_SHA}")
+      #     fi
+
+      #     ../node_modules/.bin/graph deploy "${{ steps.staging_or_not.outputs.subgraph }}" --deploy-key ${{ secrets.SUBGRAPH_ALCHEMY_HOSTED_SERVICE_DEPLOY_KEY }} --node https://subgraphs.alchemy.com/api/subgraphs/deploy --ipfs https://ipfs.satsuma.xyz --version-label "$VERSION_LABEL"
+      #   working-directory: '${{ matrix.value }}'
+
